// This file is auto-generated by UserEngine. Do not edit manually.
// Generation timestamp: 2025-07-20T23:24:33.742Z

import React from 'react';
import { ButtonProps } from '../library/Button';
import { CardProps } from '../library/Card';
import { TestNewComponentProps } from '../library/TestNewComponent';
import { InputProps } from '../library/forms/Input';
import { HeaderProps } from '../library/layout/Header';
import { TestComponentProps } from '../library/test-watch/TestComponent';

// Базовый тип для всех спеков
export interface BaseUserFace {
  id: string;
  component: string;
  meta?: {
    className?: string;
    visible?: boolean;
  };
  events?: Record<string, string>;
  [key: string]: any;
}

// UserFace - автоматически генерируется из компонентов в папке library
export type UserFace = BaseUserFace & ({ component: 'button'; props: ButtonProps; } | { component: 'card'; props: CardProps; } | { component: 'testnewcomponent'; props: TestNewComponentProps; } | { component: 'input'; props: InputProps; } | { component: 'header'; props: HeaderProps; } | { component: 'testcomponent'; props: TestComponentProps; });

// Типы для движка
export interface UserEngine {
  registerComponent(name: string, component: React.ComponentType<any>): void;
  getComponent(name: string): React.ComponentType<any> | undefined;
  getRegisteredComponents(): string[];
}

export interface UserRendererProps {
  face: UserFace;
}

export interface UserComponentProps {
  face: UserFace;
  children?: React.ReactNode;
}

// Типы зарегистрированных компонентов
// buttonProps is defined in Button.tsx
// cardProps is defined in Card.tsx
// testnewcomponentProps is defined in TestNewComponent.tsx
// inputProps is defined in forms/Input.tsx
// headerProps is defined in layout/Header.tsx
// testcomponentProps is defined in test-watch/TestComponent.tsx
